[package]
name = "queue_manager"
version = "0.1.0"
authors = ["mbilker <me@mbilker.us>"]

[[bin]]
doc = false
path = "src/main.rs"
name = "queue_manager"

[dependencies]
ansi_term	= "0.9"
redis		= "0.8.0"
serde_json	= "1.0.0"
